/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rnimour.sorters.mergesort

import java.io.File

// give absolute path so it can run both in IDE and in terminal with `gradle run`
private const val ABS_PATH = "/Users/ruudnimour/dev/projects/me/coroutines/sorters"
const val FILENAME = "$ABS_PATH/random_list_100mil.txt"

// 1   million takes ~0.06s to read, ~ 0.16s to sort
// 10  million takes ~0.5 s to read, ~ 2   s to sort
// 100 million takes ~5   s to read, ~12   s to sort

fun main() {
    println("Hello World! I am a single-threaded merge sorter. Sorting list ${FILENAME.split("/").last()}")

    val list = mutableListOf<Short>()
    time("Reading file") {
        File(FILENAME).forEachLine {
            list.add(it.toShortOrNull() ?: -1)
        }
    }

    time("Sorting") {
        mergeSort(list)
    }

    list.sanityCheckIsSorted()
}

// The merge algorithms. GitHub Copilot literally wrote all of this for me, it took away the fun part :(
fun mergeSort(list: MutableList<Short>): Any {
    if (list.size <= 1) {
        return list
    }

    val middle = list.size / 2
    val left = list.subList(0, middle)
    val right = list.subList(middle, list.size)

    mergeSort(left)
    mergeSort(right)

    merge(list, left, right)

    return list
}

fun merge(list: MutableList<Short>, left: MutableList<Short>, right: MutableList<Short>) {

    var leftIndex = 0
    var rightIndex = 0
    var listIndex = 0

    while (leftIndex < left.size && rightIndex < right.size) {
        if (left[leftIndex] < right[rightIndex]) {
            list[listIndex++] = left[leftIndex++]
        } else {
            list[listIndex++] = right[rightIndex++]
        }
    }

    while (leftIndex < left.size) {
        list[listIndex++] = left[leftIndex++]
    }

    while (rightIndex < right.size) {
        list[listIndex++] = right[rightIndex++]
    }
}
