/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rnimour.sorters.mergesort

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

class MergeSortTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = MergeSort()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
